motorpilotltd/feedback-tool

app/Http/Controllers/Auth/CustomAuthenticatedSessionController.php
app/Http/Middleware/CheckAppSettings.php
resources/views/auth/login.blade.php
resources/views/components/authentication-card.blade.php
routes/fortify.php
routes/web.php

Adds the ability to force the login screen to be displayed when AAD Only is ON.
Also allows the user to log out, when AAD Only is ON, without them immediately being logged back in.

GH-1 Ability to show login screen and logout when AAD Only is ON.

---

resources/views/_partials/breadcrumbs.blade.php
resources/views/components/accordion/item.blade.php
resources/views/components/authentication-card.blade.php
resources/views/components/product-card.blade.php
resources/views/components/tooltip-beta.blade.php
resources/views/livewire/admin/admin-users-table.blade.php
resources/views/livewire/admin/products-table.blade.php
resources/views/livewire/notification-bell.blade.php
resources/views/livewire/product/index.blade.php
resources/views/vendor/jetstream/components/authentication-card.blade.php
tailwind.config.js

This pull request contains changes for streamlining your Tailwind configuration file and utilities.
- Checkout the `shift-121928` branch
- Review all pull request comments for additional changes
- Verify your Tailwind build

Tailwind Linter

---

composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.12.0` branch.
- Checkout the `shift-ci-v11.12.0` branch

Laravel 11.12.0 Shift

---

composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.13.0` branch.
- Checkout the `shift-ci-v11.13.0` branch

Laravel 11.13.0 Shift

---

composer.json
composer.lock
package-lock.json

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.15.0` branch.
- Checkout the `shift-ci-v11.15.0` branch

Laravel 11.15.0 Shift

---

resources/views/livewire/product/ideas-progress.blade.php

To fix issue #24 
- ensure to render the idea's link

Fixed idea link in the progress page

---

app/Filters/Common/SearchField.php
app/Http/Controllers/Api/Users/Index.php
resources/views/livewire/admin/admin-users-table.blade.php
resources/views/livewire/admin/banned-users-table.blade.php
resources/views/livewire/forms/idea-form.blade.php

To fix issue #22:
- Ensure the $request was being passed in the callback functions where it is being use
- Remove profile image in the select user search

Error accessing api/users in the select user search

---

composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.16.0` branch.
- Checkout the `shift-ci-v11.16.0` branch

Laravel 11.16.0 Shift

---

app/Livewire/Admin/AdminUsersTable.php
app/Livewire/GlobalSearch.php
composer.json
composer.lock
tests/Pest.php

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.19.0` branch.
- Checkout the `shift-ci-v11.19.0` branch

Laravel 11.19.0 Shift

---

app/Livewire/Admin/AdminUsersTable.php
app/Livewire/Admin/IdeasTable.php
resources/views/livewire/admin/admin-users-table.blade.php
tests/Feature/AdminDashboard/AdminUsersTableTest.php
tests/Pest.php

To address issue: https://github.com/motorpilotltd/feedback-tool/issues/28
- Should now allow to assign multiple roles for a user
- Prioritize super admin role 
- Added new tests for user role/permissions table

Handle user multiple role

---

resources/views/components/notifications/comment.blade.php
resources/views/components/notifications/idea.blade.php
resources/views/components/user-avatar.blade.php

To fix issue: https://github.com/motorpilotltd/feedback-tool/issues/34

Ensure to fallback on user's name initials when no avatar is uploaded

---

app/Livewire/NotificationBell.php

Resolve issue when marking all as read in the notification bell.

Updated DatabaseNotification->delete() to markasRead()

---

composer.json
composer.lock

This pull request includes updates for the recent minor version release of Laravel as well as updates to your package dependencies. Feel free to commit any additional changes to the `shift-ci-v11.21.0` branch.
- Checkout the `shift-ci-v11.21.0` branch

Laravel 11.21.0 Shift

---

composer.json
composer.lock

This pull request includes updates for the recent patch version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.27.2).
- Checkout the `shift-ci-v11.27.2` branch

Laravel 11.27.2 Shift

---

composer.json
composer.lock
package-lock.json

This pull request includes updates for the recent minor version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.34.0), or highlighted changes and tips in the weekly [Shifty Bits newsletter](https://shiftybits.news).
- Checkout the `shift-ci-v11.34.0` branch

Laravel 11.34.0 Shift

---

resources/views/components/dialog-modal.blade.php

- Fixed dialog-modal component to use WireUI component

Use wieui dialog for modals

---

composer.json
composer.lock
config/debugbar.php
config/media-library.php
config/permission.php

This pull request includes updates for the recent minor version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.37.0), or highlighted changes and tips in the weekly [Shifty Bits newsletter](https://shiftybits.news).
- Checkout the `shift-ci-v11.37.0` branch

Laravel 11.37.0 Shift

---

app/Livewire/Admin/ProductsTable.php
app/Livewire/Admin/SystemSettings.php
app/Livewire/Forms/LinksField.php
app/Traits/Livewire/WithLinksField.php
resources/views/api/api-token-manager.blade.php
resources/views/livewire/forms/links-field.blade.php

Update wire:change to wire:model.change to update product's links property

[Fix] Fixed saving product links

---

app/Models/User.php
composer.json
composer.lock
database/factories/UserFactory.php
database/migrations/2025_01_22_091658_add_missing_two_factor_colun_to_users_table.php

This pull request includes updates for the recent minor version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.39.0), or highlighted changes and tips in the weekly [Shifty Bits newsletter](https://shiftybits.news).
- Checkout the `shift-ci-v11.39.0` branch

Laravel 11.39.0 Shift

---

composer.json
composer.lock

This pull request includes updates for the recent patch version release of Laravel as well as bumps your package dependencies. You may review the full list of changes in the [Laravel Release Notes](https://github.com/laravel/framework/releases/tag/v11.41.3).
- Checkout the `shift-ci-v11.41.3` branch

Laravel 11.41.3 Shift
